//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by ClientDemo.rc
//
#define IDM_ABOUTBOX                    0x0010
#define IDD_ABOUTBOX                    100
#define IDS_ABOUTBOX                    101
#define IDD_CLIENTDEMO_DIALOG           102
#define IDD_DIG_FORBIDDIRECTION         103
#define IDR_MAINFRAME                   128
#define IDD_CONFIG_DLG                  129
#define IDD_DEVICE_DLG                  131
#define IDD_PTZ_DLG                     132
#define IDD_COLOR_DLG                   133
#define IDD_VIDEO_WND                   134
#define IDD_REMOTE_PLAYBACK             135
#define IDD_DEV_CONFIG                  136
#define IDD_KEYBOARD_DLG                137
#define IDD_DLG_NETALARM                138
#define IDD_CRUISEEDIT                  139
#define IDD_VIDEOPLAY                   140
#define IDD_DLG_TAB_PLAYBACK            141
#define IDD_DLG_LOCALPLAYBACK           142
#define IDD_DIALOG_IPEdit               144
#define IDC_STATIC_MSG                  145
#define IDD_DLG_PROMPT                  145
#define IDD_DLG_TESTCOVER               146
#define IDC_TREE1                       1000
#define IDC_EDIT_DEVICE_NAME            1005
#define IDC_EDIT_PORT                   1007
#define IDC_EDIT_USERNAME               1008
#define IDC_EDIT_PSW                    1009
#define IDC_EDIT_TOTALCHANNEL           1010
#define IDC_BUTTONLEFT                  1010
#define IDC_IPADDRESS1                  1011
#define IDC_BUTTONDOWN                  1011
#define IDC_IPADDRESS_IP                1011
#define IDC_BUTTONUP                    1012
#define IDC_BTN_DEVICE                  1012
#define IDC_IPADDRESS2                  1012
#define IDC_IPADDRESS_Mask              1012
#define IDC_BUTTONRIGHT                 1013
#define IDC_BTN_PTZ                     1013
#define IDC_IPADDRESS3                  1013
#define IDC_IPADDRESS_Gateway           1013
#define IDC_BUTTONTJLEFT                1014
#define IDC_BTN_COLOR                   1014
#define IDC_BUTTONJJLEFT                1015
#define IDC_BTN_PLAYBACK                1015
#define IDC_BUTTONGQLEFT                1016
#define IDC_BTN_CAPTURE                 1016
#define IDC_BUTTONTJRIGHT               1017
#define IDC_BTN_SAVE                    1017
#define IDC_BUTTONJJRIGHT               1018
#define IDC_COMBO_DEVICE                1018
#define IDC_BTN_DEV_CONFIG              1018
#define IDC_BUTTONGQRIGHT               1019
#define IDC_COMBO_CHANNEL               1019
#define IDC_BTN_DEV_KEYBOARD            1019
#define IDC_BUTTONPOLL                  1020
#define IDC_COMBO_TYPE                  1020
#define IDC_BTN_NET_ALARM               1020
#define IDC_DATE_BEGIN                  1021
#define IDC_SLIDERDBD                   1022
#define IDC_TIME_BEGIN                  1022
#define IDC_SLIDERBHD                   1023
#define IDC_DATE_END                    1023
#define IDC_SLIDERSD                    1024
#define IDC_TIME_END                    1024
#define IDC_SLIDERYL                    1025
#define IDC_LIST1                       1025
#define IDC_SEARCH                      1026
#define IDC_DOWNLOAD                    1027
#define IDC_STATIC_VIDEO                1028
#define IDC_PLAY                        1029
#define IDC_STOP                        1030
#define IDC_FAST                        1031
#define IDC_SLOW                        1032
#define IDC_PROGRESS1                   1033
#define IDC_PAUSE                       1034
#define IDC_COMBO1                      1036
#define ID_KEY_0                        1037
#define IDC_COMBO2                      1037
#define ID_KEY_1                        1038
#define ID_KEY_2                        1039
#define ID_KEY_3                        1040
#define ID_KEY_4                        1041
#define ID_KEY_5                        1042
#define ID_KEY_6                        1043
#define ID_KEY_7                        1044
#define ID_KEY_8                        1045
#define ID_KEY_9                        1046
#define ID_KEY_10                       1047
#define ID_KEY_11                       1048
#define ID_KEY_12                       1049
#define ID_KEY_13                       1050
#define ID_KEY_14                       1051
#define ID_KEY_15                       1052
#define ID_KEY_16                       1053
#define IDC_STATIC_ZOOM                 1055
#define IDC_STATIC_IRIS                 1056
#define IDC_CHECK_TIME                  1056
#define IDC_STATIC_FOCUS                1057
#define IDC_CHECK_NAME                  1057
#define IDC_BTN_START                   1057
#define ID_KEY_10PlUS                   1058
#define IDC_CHECK_TIME2                 1058
#define IDC_BTN_STOP                    1058
#define IDC_CHECK_NAME2                 1059
#define IDC_CMB_CHANNEL                 1059
#define IDC_KEY_ESC                     1060
#define IDC_KEY_ENTER                   1061
#define IDC_KEY_MENU                    1062
#define IDC_KEY_UP                      1063
#define IDC_BUTTONLEFTUP                1063
#define IDC_KEY_LEFT                    1064
#define IDC_BUTTONRIGHTUP               1064
#define IDC_KEY_RIGHT                   1065
#define IDC_BUTTONLEFTDOWN              1065
#define IDC_KEY_DOWN                    1066
#define IDC_BUTTONRIGHTDOWN             1066
#define IDC_KEY_SPLIT                   1067
#define IDC_UsePresent                  1067
#define IDC_KEY_SPLIT_1                 1068
#define IDC_ADDPRESENT                  1068
#define IDC_KEY_SPLIT_4                 1069
#define IDC_PRESENTDELETE               1069
#define IDC_BUTTONADDPRESENT            1069
#define IDC_KEY_SPLIT_8                 1070
#define IDC_BUTTONDELETEPRESENT         1070
#define IDC_KEY_SPLIT_9                 1071
#define IDC_BUTTONDELETECRUISE          1071
#define IDC_KEY_SPLIT_16                1072
#define IDC_CRUISEEDIT                  1072
#define IDC_EDIT1                       1072
#define IDC_KEY_PLAY                    1073
#define IDC_CRUISEPLAY                  1073
#define IDC_COMBOWNDNUM                 1074
#define IDC_KEY_STOP                    1074
#define IDC_CRUISESTOP                  1074
#define IDC_KEY_BACK                    1075
#define IDC_KEY_FAST                    1076
#define IDC_KEY_SLOW                    1077
#define IDC_KEY_NEXT                    1078
#define IDC_KEY_PREV                    1079
#define IDC_TAB1                        1079
#define IDC_BUTTON_OPEN                 1080
#define IDC_KEY_PTZ_UP                  1081
#define IDC_BUTTON_PLAY                 1081
#define IDC_KEY_SEARCH                  1082
#define IDC_BUTTON_STOP                 1082
#define IDC_SLIDERLD                    1083
#define IDC_KEY_RECORD                  1083
#define IDC_BUTTON_PAUSE                1083
#define IDC_KEY_PTZ_LEFT                1084
#define IDC_BUTTON_FAST                 1084
#define IDC_KEY_INFO                    1085
#define IDC_BUTTON_SLOW                 1085
#define IDC_KEY_ALARM                   1086
#define IDC_STATIC_PLAYWINDOW           1086
#define IDC_KEY_BACKUP                  1087
#define IDC_KEY_SHUTDOWN                1088
#define IDC_BUTTON1                     1088
#define IDC_BUTTON1_TestDev             1088
#define IDC_BTN_Test                    1088
#define IDC_PAGE_UP                     1088
#define IDC_BTN_GETINFO                 1088
#define IDC_KEY_PTZ_RIGHT               1089
#define IDC_EDIT_SVR                    1089
#define IDC_KEY_PTZ_DOWN                1090
#define IDC_BUTTON_setttingDev          1090
#define IDC_BTN_Setting                 1090
#define IDC_KEY_ZOOM_TELE               1091
#define IDC_BTN_Search                  1091
#define IDC_KEY_ZOOM_WIDE               1092
#define IDC_LIST_Upgrade                1092
#define IDC_KEY_IRIS_LARGE              1093
#define IDC_EDIT2                       1093
#define IDC_EDIT_Tcp                    1093
#define IDC_EDIT_HOSTPORT               1093
#define IDC_EDIT_DesPath                1093
#define IDC_KEY_IRIS_SMALL              1094
#define IDC_EDIT3                       1094
#define IDC_EDIT_Mac                    1094
#define IDC_EDIT_SERIALID               1094
#define IDC_KEY_FOCUS_FAR               1095
#define IDC_EDIT_Http                   1095
#define IDC_KEY_FOCUS_NEAR              1096
#define IDC_STATIC_                     1096
#define IDC_KEY_PTZ                     1097
#define IDC_PAGE_DOWN                   1097
#define IDC_KEY_SHIFT                   1098
#define IDC_LIST_DDNS_DEV               1098
#define IDC_CHECK_OSD                   1098
#define IDC_KEY_FUNC                    1099
#define IDC_EDIT_HOSTIP                 1099
#define IDC_KEY_SET_PRESET              1100
#define IDC_BUTTON2                     1100
#define IDC_KEY_GO_PRESET               1101
#define IDC_EDIT_SrcPath                1101
#define IDC_KEY_DEL_PRESET              1102
#define IDC_SLIDERFILE                  1102
#define IDC_KEY_AUTO_TOUR               1103
#define IDC_KEY_AUTO_PAN                1104
#define IDC_CHECK_IP                    1104
#define IDC_CHECK_SerialID              1105
#define IDC_BUTTON_Audio                1105
#define IDC_SLIDER_BACKPLAY             1106
#define IDC_KEY_AUTO_SCAN               1112
#define IDC_STATIC11                    1336
#define IDC_STATIC12                    1338
#define IDC_STATIC13                    1340
#define IDC_STATIC_CMBWND               1347
#define IDC_STATIC4                     1352
#define IDC_STATIC5                     1500
#define IDC_STATIC6                     1501
#define IDC_STATIC7                     1502
#define IDC_STATIC8                     1503
#define IDC_STATIC9                     1504
#define IDC_STATIC10                    1505
#define IDC_STATIC14                    1506
#define IDC_RADIO_DIRECTION1            4626
#define IDC_RADIO_DIRECTION2            4627
#define IDC_RADIO_DIRECTION3            4628

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        147
#define _APS_NEXT_COMMAND_VALUE         32771
#define _APS_NEXT_CONTROL_VALUE         1107
#define _APS_NEXT_SYMED_VALUE           104
#endif
#endif
